# -*- coding: utf-8 -*-
"""2 Object localizator with segmentation for self-driving car.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tkCSRElxIQpQazz4lj9GWxVPbumXzFMH
"""



# Update fastai
!pip install fastai --upgrade

from fastai.vision.all import *
path = untar_data(URLs.CAMVID_TINY)
dls = SegmentationDataLoaders.from_label_func(
    path, bs=8, fnames = get_image_files(path/"images"),
    label_func = lambda o:
path/'labels'/f'{o.stem}_P{o.suffix}',
codes = np.loadtxt(path/'codes.txt', dtype=str)
)

learn = unet_learner(dls, resnet34)

learn.fine_tune(8)

learn.show_results(max_n=4, figsize=(7,8))